server:
  port: 8080
  mode: "dev"
postgres:
  host: 127.0.0.1
  port: 5432
  username: "your_username"
  password: "your_password"
  dbname: testdevgo
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.xxx.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
jwt:
  access_token_key: ""
  access_token_expires_in:
  refresh_token_key: ""
  refresh_token_expires_in:
